version: "3.4"

services:
    traefik:
        image: "traefik:v2.2"
        command:
            - "--api.insecure=true"
            - "--providers.rest=true"
            - "--providers.rest.insecure=true"
            - "--entrypoints.web.address=:5001"
            - "--entrypoints.traefik.address=:8081"
        restart: unless-stopped
        networks:
            - traefik_gate
            - mistic_service_gate
        ports:
            - "5001:5001"
            - "8081:8081"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
    traefik_gate:
        driver: bridge
    mistic_service_gate:
        external:
            name: mistic_service_gate
