FROM perl:5.30.0 AS perl_base
FROM python:3.8.10 AS backend_base
LABEL maintainer="Eloy Adonis Colell <eloy.colell@gmail.com>"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y gcc
COPY --from=perl_base /usr/local/lib/perl5 /usr/local/lib/perl5
COPY --from=perl_base /usr/local/bin/perl /usr/local/bin/perl
COPY --from=perl_base /usr/local/bin/cpan /usr/local/bin/cpan
COPY --from=perl_base /usr/local/bin/cpanm /usr/local/bin/cpanm
COPY --from=perl_base /usr/bin/make /usr/bin/make
COPY --from=perl_base /usr/bin/perl /usr/bin/perl
ENV PERL5LIB="/usr/local/lib/site_perl:$PERL5LIB"
RUN echo $PATH
RUN echo $PERL5LIB
RUN cpanm -v Moose IPC::Run

ENV PYTHONUNBUFFERED True
WORKDIR /home/pfamserver/requirements
RUN poetry config virtualenvs.create false \
  && poetry install --no-dev --no-interaction --no-ansi

WORKDIR /home/pfamserver/stage

FROM backend_base as backend_web

WORKDIR /home/pfamserver/stage

ENV FLASK_ENV SQLALCHEMY_DATABASE_URI NODE_ENV SERVER_NAME FLASK_APP PFAM_VERSION HMMER_VERSION

EXPOSE 5000 4369

FROM mysql:8.0.26 as mysql
FROM backend_web as backend_dev

WORKDIR /home/pfamserver/requirements
RUN poetry install --no-interaction --no-ansi
COPY --from=mysql /usr/bin/mysql /usr/bin/mysql
