from database import db


class PfamA(db.Model):
    __tablename__ = 'pfamA'

    pfamA_acc = db.Column(db.Unicode(7), primary_key=True)
    pfamA_id = db.Column(db.Unicode(16))
    previous_id = db.Column(db.Unicode)
    description = db.Column(db.Unicode(100))
    author = db.Column(db.Unicode)
    deposited_by = db.Column(db.Unicode(100))
    seed_source = db.Column(db.Unicode)
    type = db.Column(db.Enum('Family', 'Domain', 'Repeat', 'Motif', 'Disordered', 'Coiled-coil'))
    comment = db.Column(db.Unicode)
    sequence_GA = db.Column(db.Numeric(8,2))
    domain_GA = db.Column(db.Numeric(8,2))
    sequence_TC = db.Column(db.Numeric(8,2))
    domain_TC = db.Column(db.Numeric(8,2))
    sequence_NC = db.Column(db.Numeric(8,2))
    domain_NC = db.Column(db.Numeric(8,2))
    buildMethod = db.Column(db.Unicode)
    model_length = db.Column(db.Integer)
    searchMethod = db.Column(db.Unicode)
    msv_lambda = db.Column(db.Numeric(8,2))
    msv_mu = db.Column(db.Numeric(8,2))
    viterbi_lambda = db.Column(db.Numeric(8,2))
    viterbi_mu = db.Column(db.Numeric(8,2))
    forward_lambda = db.Column(db.Numeric(8,2))
    forward_tau = db.Column(db.Numeric(8,2))
    num_seed = db.Column(db.Integer)
    num_full = db.Column(db.Integer)
    updated = db.Column(db.DateTime)
    created = db.Column(db.DateTime)
    version = db.Column(db.Integer)
    number_archs = db.Column(db.Integer)
    number_species = db.Column(db.Integer)
    number_structures = db.Column(db.Integer)
    number_ncbi = db.Column(db.Integer)
    number_meta = db.Column(db.Integer)
    average_length = db.Column(db.Numeric(6,2))
    percentage_id = db.Column(db.Integer)
    average_coverage = db.Column(db.Numeric(6,2))
    change_status = db.Column(db.Unicode)
    seed_consensus = db.Column(db.Unicode)
    full_consensus = db.Column(db.Unicode)
    number_shuffled_hits = db.Column(db.Integer)
    number_uniprot = db.Column(db.Integer)
    rp_seed = db.Column(db.Integer)
    number_rp15 = db.Column(db.Numeric(8))
    number_rp35 = db.Column(db.Numeric(8))
    number_rp55 = db.Column(db.Numeric(8))
    number_rp75 = db.Column(db.Numeric(8))
