"""empty message

Revision ID: ada2265ade71
Revises: None
Create Date: 2017-11-25 16:09:46.079561

"""

# revision identifiers, used by Alembic.
revision = 'ada2265ade71'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.choice
from pfamserver.models.version import VersionStatus


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.UnicodeText(), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(VersionStatus), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    # ### end Alembic commands ###
