name: Backend workflow
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
      - '!production'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Testing
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04.4]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test over 3.8.10
      run: make pipeline-backend-test
  mypy:
    name: Mypy
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04.4]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Mypy over 3.8.10
      run: make pipeline-backend-mypy
  quality:
    name: Quality
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04.4]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Quality over 3.8.10
      run: make pipeline-backend-quality
